services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '127.0.0.1:8888:8080'
    depends_on:
      - postgres
    networks:
      - scriptty-network
    env_file:
      - .env

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - scriptty-network

volumes:
  postgres-db:

networks:
  scriptty-network:
    driver: bridge
