services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '127.0.0.1:8888:8080' # Change depending on the port set in Dockerfile
    # depends_on:
    #   - postgres
    networks:
      - scriptty-network
    env_file:
      - .env

# Uncomment if you do not have Postgres running externally
#   postgres:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: ${DB_USERNAME}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#       POSTGRES_DB: ${DB_DATABASE}
#     env_file:
#       - .env
#     ports:
#       - '127.0.0.1:5432:5432'
#     volumes:
#       - postgres-db:/var/lib/postgresql/data
#     networks:
#       - scriptty-network

# volumes:
#   postgres-db:

networks:
  scriptty-network:
    driver: bridge
