services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'

volumes:
  postgres-db:
